apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: postgres-operator
  template:
    metadata:
      labels:
        application: postgres-operator
    spec:
      serviceAccountName: postgres-operator-sa
      containers:
      - name: postgres-operator
        image: ghcr.io/ocf/postgres-operator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pg-op-secret
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pg-op-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pg-op-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: pg-op-secret
              key: DB_PASS