---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: postgres-operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: postgres-operator-role-cluster
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]

  # Application: access for watching cluster-wide.
  - apiGroups: [ocf.io]
    resources: [postgrespairs]
    verbs: [list, watch, patch, get]

  # We create secrets but don't want to be able to access them.
  - apiGroups: [""]
    resources: [secrets]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: postgres-operator-role-namespaced
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [ocf.io]
    resources: [postgrespairs]
    verbs: [list, watch, patch, get]

  # Application: other resources it produces and manipulates.
  # We create secrets but don't want to be able to access them.
  - apiGroups: [""]
    resources: [secrets]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: postgres-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgres-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: postgres-operator-sa
    namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: postgres-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: postgres-operator-sa